- hosts: servers
  # roles:
  #   - { role: datadog.datadog, become: yes }
  vars_files:
    - secret.yml
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_site: "datadoghq.com"
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd']
          - name: syslog
            search_string: ['rsyslog']
            cpu_check_interval: 0.2
            exact_match: true
            ignore_denied_access: true